pipeline {
    agent any
    stages {
        stage('GatherConfiguration') {
            steps {
                "${WORKSPACE}/code-server/jenkins/config.sh"
            }
        }
        stage('CreateRootlayout') {
            steps {
                "${WORKSPACE}/code-server/jenkins/rootlayout.sh"
            }
        }
        stage('Build_BUILDIMAGE') {
            steps {
                "${WORKSPACE}/code-server/jenkins/build_build_image.sh"
            }
        }
        stage('Build_VSCODE') {
            steps {
                "${WORKSPACE}/code-server/jenkins/build_vscode.sh"
            }
        }
    }
}